ci build linux/x86

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -28,8 +28,8 @@ jobs:
           - {os: windows-2022,   arch: win32,    config: RelWithDebInfo}
           - {os: windows-2022,   arch: arm64,    config: RelWithDebInfo}
           - {os: windows-2022,   arch: arm,      config: RelWithDebInfo}
-          # - {os: ubuntu-2204,    arch: x64,      config: RelWithDebInfo} # runner fails for some reason, works fine locally: see https://github.com/actions/runner-images/discussions/7188
-          # - {os: ubuntu-2204,    arch: x86,      config: RelWithDebInfo}
+          - {os: ubuntu-2204,    arch: x64,      config: RelWithDebInfo} # runner fails for some reason, works fine locally: see https://github.com/actions/runner-images/discussions/7188
+          - {os: ubuntu-2204,    arch: x86,      config: RelWithDebInfo}
 
     runs-on: ${{ matrix.variants.os }}
     outputs:
@@ -37,8 +37,8 @@ jobs:
       windows-2022-win32: ${{ join(steps.*.outputs.windows-2022-win32,'') }}
       windows-2022-arm: ${{ join(steps.*.outputs.windows-2022-arm,'') }}
       windows-2022-arm64: ${{ join(steps.*.outputs.windows-2022-arm64,'') }}
-      # ubuntu-2204-x64: ${{ join(steps.*.outputs.ubuntu-2204-x64,'') }}
-      # ubuntu-2204-x86: ${{ join(steps.*.outputs.ubuntu-2204-x86,'') }}
+      ubuntu-2204-x64: ${{ join(steps.*.outputs.ubuntu-2204-x64,'') }}
+      ubuntu-2204-x86: ${{ join(steps.*.outputs.ubuntu-2204-x86,'') }}
 
     steps:
     - uses: actions/checkout@v4
@@ -58,10 +58,22 @@ jobs:
         wget -O /tmp/llvm.sh https://apt.llvm.org/llvm.sh
         chmod +x /tmp/llvm.sh
         sudo /tmp/llvm.sh 17
-        sudo apt update && sudo apt install -y cmake doxygen clang-17 libc++abi-17-dev libc++-17-dev llvm-17-dev nasm
+        sudo apt update && sudo apt install -y cmake doxygen clang-17 libc++abi-17-dev libc++-17-dev llvm-17-dev nasm gcc-multilib g++-multilib
         echo "NB_CPU=$(grep -c ^processor /proc/cpuinfo)" >> $GITHUB_ENV
-        echo "CC=clang-17" >> $GITHUB_ENV
-        echo "CXX=clang++-17" >> $GITHUB_ENV
+        case "${{ matrix.variants.arch }}" in
+          x86)
+          echo "CC=clang-17 -m32" >> $GITHUB_ENV
+          echo "CXX=clang++-17 -m32" >> $GITHUB_ENV
+          ;;
+          x64)
+          echo "CC=clang-17" >> $GITHUB_ENV
+          echo "CXX=clang++-17" >> $GITHUB_ENV
+          ;;
+          *)
+          echo "Invalid architecture"
+          exit 1
+          ;;
+        esac
 
     - name: Prepare common environment
       run: |
